[package]
name = "rust-pong-basic"
version = "0.1.0"
edition = "2024"

[dependencies]
ferris-says = "0.3.2"
soloud = "1.1"
rand = "0.9.2"
# sdl2 = "0.38"

[dependencies.sdl2]
version = "0.38"
default-features = false
features = ["image"]
